### PR TITLE
[HOPSWORKS-1273] Install base admin software on the machines

### PR DESCRIPTION
**Pull request by SirOibaf**

### CODE REVIEW

**Comment by jimdowling** [comment]
Are you really sure you want to put emacs on there? Most admins i know would think it is way overkill. It's >100MB+, i think.

**Comment by SirOibaf** [comment]
I don't use it so I don't have strong opinions for/against it. It was requested by @kouzant. Yes, emacs is quite large, but probably negligible considering the overall size of the Hopsworks installation.

**Comment by kouzant** [comment]
emacs package brings a lot of dependencies, UI included. I install
emacs25-nox instead, Centos might have an older version. It's not
necessary, just for my convenience, I can install it manually

--

**Comment by jimdowling** [comment]
I am an emacs user, program all chef/bash/python with it. But i use vi when sysadmin, as i think 95+% of sysadmins do. Just because our distro is already 10GBs, doesn't mean we need to add another 100MB+ to it. IMO.

**Pull request merged**
